name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add local bin to PATH
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Install python packages and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv libapt-pkg-dev
          python3 -m venv ${HOME}/.venv
          source ${HOME}/.venv/bin/activate
          pip install -U pip wheel setuptools
          pip install -U -r requirements.txt -r requirements-dev.txt -r requirements-focal.txt
          pip install -e .
      - name: Run black
        run: |
          source ${HOME}/.venv/bin/activate
          make test-black
      - name: Run codespell
        run: |
          source ${HOME}/.venv/bin/activate
          make test-codespell
      - name: Run flake8
        run: |
          source ${HOME}/.venv/bin/activate
          make test-flake8
      - name: Run isort
        run: |
          source ${HOME}/.venv/bin/activate
          make test-isort
      - name: Run mypy
        run: |
          source ${HOME}/.venv/bin/activate
          make test-mypy
      - name: Run pydocstyle
        run: |
          source ${HOME}/.venv/bin/activate
          make test-pydocstyle
      - name: Run pyright
        run: |
          sudo apt install -y npm
          sudo npm install -g pyright
          source ${HOME}/.venv/bin/activate
          make test-pyright

  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: [3.7, 3.8]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Add local bin to PATH
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-venv libapt-pkg-dev
          python3 -m venv ${HOME}/.venv
          source ${HOME}/.venv/bin/activate
          pip install -U pip wheel setuptools
          case "${{ matrix.os }}" in
            ubuntu-18.04)
              # pip 20.2 breaks python3-apt, so pin the version before building
              pip install pip==20.1
              pip install -U -r requirements-bionic.txt
              ;;
            ubuntu-20.04)
              pip install -U -r requirements-focal.txt
              ;;
          esac
          pip install -U -r requirements.txt -r requirements-dev.txt
          pip install -e .
      - name: Run unit tests
        run: |
          source ${HOME}/.venv/bin/activate
          make test-units
      - name: Run integration tests
        run: |
          source ${HOME}/.venv/bin/activate
          make test-integrations
